apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana-pgsql-template
  namespace: smartcity
  annotations: {}
parameters:
  - description: Name of the database
    name: db_database
  - description: DB user
    name: db_user
  - description: DB password
    name: db_password
objects:
  - apiVersion: integreatly.org/v1alpha1
    kind: GrafanaDataSource
    metadata:
      name: pgsql-grafana-datasource
      namespace: smartcity
    spec:
      datasources:
        - name: PostgreSQL
          type: postgres
          typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
          access: proxy
          url: "smartcity-db-service:5432"
          password: ${db_password}
          user: ${db_user}
          database: ${db_database}
          basicAuth: false
          isDefault: false
          jsonData:
            postgresVersion: 903
            sslmode: disable
          readOnly: false
      name: grafana-pgsql-datasource.yaml
