apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: core-kafka
  namespace: smartcity
  labels:
    app: core-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      class: ocs-storagecluster-ceph-rbd
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      class: ocs-storagecluster-ceph-rbd
