apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: mirror-maker
  namespace: smartcity
spec:
  consumer:
    bootstrapServers: "edge-kafka-kafka-bootstrap:9092"
    groupId: mirror-maker-group-id
  producer:
    bootstrapServers: "core-kafka-kafka-bootstrap:9092"
  replicas: 1
  whitelist: lpr
